package dnswriter

import (
	"fmt"
	"os"
	"sort"
	"sync"
)

type Container struct {
	ID     string
	Name   string
	Labels map[string]string
	State  string
}

type DNSWriter struct {
	filePath string
	mu      sync.Mutex
}

func New(filePath string) *DNSWriter {
	return &DNSWriter{filePath: filePath}
}

func (d *DNSWriter) Write(containers []Container, hostIP string) error {
	d.mu.Lock()
	defer d.mu.Unlock()

	file, err := os.Create(d.filePath)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintf(file, "# Generated by pihole-docker-dns\n")
	fmt.Fprintf(file, "# Do not edit manually - this file is overwritten\n\n")

	sort.Slice(containers, func(i, j int) bool {
		return containers[i].Name < containers[j].Name
	})

	for _, c := range containers {
		if c.State != "running" {
			continue
		}
		fmt.Fprintf(file, "address=/%s/%s\n", c.Name, hostIP)
	}

	return nil
}

func (d *DNSWriter) FilePath() string {
	return d.filePath
}